# Change these first
owner: Voice-Mate # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
assignees:
  - two-trick-pony-NL

sites:
  - name: Website and Mobile App
    url: https://voicemate.nl/fastapistatus
    maxResponseTime: 3000
    __dangerous__body_degraded: "Offline for Maintenance"
  - name: Networking and load balancer
    url: https://voicemate.nl/healthcheck
  - name: Task Processor
    url: https://voicemate.nl/redisstatus
    __dangerous__body_down_if_text_missing: '"status":"up"'
    maxResponseTime: 1000
  - name: Database
    url: https://voicemate.nl/databasestatus
    __dangerous__body_down_if_text_missing: '"status":"up"'
  - name: AI Call Services
    url: https://status.vapi.ai
    __dangerous__body_down_if_text_missing: 'All services are online'
  - name: Large Language Model (OpenAI)
    url: https://status.openai.com/
    __dangerous__body_down_if_text_missing: 'All Systems Operational'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voicemate.nl
  #baseUrl: /status-page
  logoUrl: https://avatars.githubusercontent.com/u/166385585?s=200&v=4
  name: Voice Mate
  introTitle: "**Voicemate** Status page."
  introMessage: This is the status page for Voice Mate. It shows any downtime and opens an issue if there is downtime.
  theme: light
  css: "body {background-color: #fafafa;}"

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Homepage
      href: https://voicemate.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
