# Change these first
owner: Voice-Mate # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
assignees:
  - two-trick-pony-NL

sites:
  - name: Voice Mate Application API
    url: https://voicemate.nl/fastapistatus
    maxResponseTime: 3000
    __dangerous__body_degraded: "Offline for Maintenance"
  - name: Reverse Proxy (nginx) 
    url: https://voicemate.nl/healthcheck
  - name: Persistent Database Server (DynamoDB)
    url: https://voicemate.nl/databasestatus
    __dangerous__body_down_if_text_missing: '"status":"up"'
  - name: In-Memory Database Server(Redis)
    url: https://voicemate.nl/redisstatus
    __dangerous__body_down_if_text_missing: '"status":"up"'
    maxResponseTime: 1000
  - name: Background Task Queue/Worker
    url: https://voicemate.nl/failed_tasks
    __dangerous__body_down_if_text_missing: '"status":"up"'
    maxResponseTime: 1000
  - name: Payment Services (Stripe)
    url: https://voicemate.nl/stripestatus
    __dangerous__body_down_if_text_missing: '"status":"up"'
  - name: Phone Call Handling (Twilio)
    url: https://voicemate.nl/twiliostatus
    __dangerous__body_down_if_text_missing: '"status":"up"'
  - name: Development/Test environment
    url: https://triage-voicemate-backend.sou81r6ngg1is.eu-central-1.cs.amazonlightsail.com/fastapistatus
    maxResponseTime: 3000
    __dangerous__body_degraded: "Offline for Maintenance"
  - name: AI-Powered Voice Processing Services (Vapi)
    url: https://status.vapi.ai
    __dangerous__body_degraded_if_text_missing: 'All services are online'
  - name: Large Language Model (OpenAI)
    url: https://status.openai.com/
    __dangerous__body_degraded_if_text_missing: 'All Systems Operational'
  - name: Usage Analytics (Mixpanel)
    url: https://www.mixpanelstatus.com/
    __dangerous__body_degraded_if_text_missing: 'All Systems Operational'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voicemate.nl
  #baseUrl: /status-page
  logoUrl: https://avatars.githubusercontent.com/u/166385585?s=200&v=4
  name: Voice Mate
  introTitle: "**Voicemate** Status page."
  introMessage: This is the status page for Voice Mate. It shows any downtime and opens an issue if there is downtime.
  theme: light
  css: "body {background-color: #fafafa;}"

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Homepage
      href: https://voicemate.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
