
# Change these first
owner: Voice-Mate # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
assignees:
  - two-trick-pony-NL

sites:
  - name: Website and Mobile App
    url: https://prod-voicemate-backend.sou81r6ngg1is.eu-central-1.cs.amazonlightsail.com/fastapistatus
    maxResponseTime: 3000
    __dangerous__body_degraded: "Offline for Maintenance"
  - name: Networking and load balancer
    url: http://prod-voicemate-backend.sou81r6ngg1is.eu-central-1.cs.amazonlightsail.com/healthcheck
    maxResponseTime: 1000
  - name: AI Call Services
    url: https://status.vapi.ai
    __dangerous__body_down_if_text_missing: 'All services are online'
  - name: Billing and Payments
    url: https://status.stripe.com
    __dangerous__body_down_if_text_missing: 'All systems operational'


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voicemate.nl
  #baseUrl: /status-page
  logoUrl: https://avatars.githubusercontent.com/u/166385585?s=200&v=4
  name: Voice Mate
  introTitle: "**Voicemate** Status page."
  introMessage: This is the status page for Voice Mate. It shows any downtime and opens an issue if there is downtime.
  theme: light
  css: "body {background-color: #fafafa;}"


  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Homepage
      href: https://voicemate.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
