
# Change these first
owner: Voice-Mate # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
assignees:
  - two-trick-pony-NL

sites:
  - name: Voice Mate Homepage
    url: https://voicemate.nl
  - name: Voicemate Server
    url: https://voicemate.nl/aws/healthcheck/
  - name: Voicemate reverse proxy
    url: https://voicemate.nl/healthcheck
  - name: Voicemate Available Phone numbers
    url: https://voicemate.nl/api/switchboard/available-phone-numbers/
    __dangerous__body_down: "running low"
  - name: Triage Mate Homepage
    url: https://triage.voicemate.nl
  - name: Triage Voicemate Server
    url: https://triage.voicemate.nl/aws/healthcheck/
  - name: Triage Voicemate reverse proxy
    url: https://triage.voicemate.nl/healthcheck
  - name: API Documentation
    url: https://voicemate.nl/docs
  - name: Partner bland.ai
    url: https://www.bland.ai/
  - name: Partner twilio
    url: https://www.twilio.com/en-us

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voicemate.nl
  #baseUrl: /status-page
  logoUrl: https://avatars.githubusercontent.com/u/166385585?s=200&v=4
  name: Voice Mate
  introTitle: "**Voicemate** Status page."
  introMessage: This is the status page for Voice Mate. It shows any downtime and opens an issue if there is downtime.
  theme: light
  css: "body {background-color: #fafafa;}"


  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Homepage
      href: https://voicemate.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
